### ISSUE TITLE
Prototipar

### ISSUE THREAD

**Issue by emrodk** [Godot-en-Espanol/Node-City#2]
Prototipar  movimiento (grilla o libre) y como romper ladrillos
Cuenten en discussions lo que van a prototipar, de esa manera se debate y al mismo tiempo el resto puede prototipar una solución diferente

**Comment by LeandroCuello** [comment]
#3 Mi solucion, falta trabajar.

**Comment by emrodk** [comment]
Elegimos el prototipo de leandro
